modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL=""
license="MIT"
[[mods]]
modId="generalmod"
version="${file.jarVersion}"
displayName="CraftTweaker"
displayURL="https://minecraft.curseforge.com/projects/crafttweaker"
updateJSONURL="https://updates.blamejared.com/get?n=crafttweaker&gv=1.16.5"
logoFile="logo.png"
authors="Jaredlll08, Kindlich and StanH"
description="Customize your minecraft experience!"